version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fundraising_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fundraising-network

  web:
    build: .
    container_name: fundraising_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fundraising
      - ADMIN_CREATION_TOKEN=secret_admin_token
      - STRIPE_SECRET_KEY=stripe_secret
    networks:
      - fundraising-network
    volumes:
      - .:/app

volumes:
  db_data:

networks:
  fundraising-network:
    driver: bridge
