"""Updated the project table

Revision ID: 16d453737fac
Revises: db8c99cf0a40
Create Date: 2025-01-08 11:55:57.613032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d453737fac'
down_revision: Union[str, None] = 'db8c99cf0a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('fundingType', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('minInvestment', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('email', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('address', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('personalizedMessage', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('motivationLetter', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('campaignCategory', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('campaignDescription', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('campaignTitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'campaignTitle')
    op.drop_column('projects', 'campaignDescription')
    op.drop_column('projects', 'campaignCategory')
    op.drop_column('projects', 'motivationLetter')
    op.drop_column('projects', 'personalizedMessage')
    op.drop_column('projects', 'phone')
    op.drop_column('projects', 'address')
    op.drop_column('projects', 'email')
    op.drop_column('projects', 'minInvestment')
    op.drop_column('projects', 'fundingType')
    op.drop_column('projects', 'deadline')
    # ### end Alembic commands ###
