"""fi

Revision ID: 5574f6afb0d7
Revises: ef7c8d500b38
Create Date: 2025-01-09 00:30:06.181277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5574f6afb0d7'
down_revision: Union[str, None] = 'ef7c8d500b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investors', sa.Column('investmentSector', sa.String(), nullable=True))
    op.drop_column('investors', 'investmetSector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investors', sa.Column('investmetSector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('investors', 'investmentSector')
    # ### end Alembic commands ###
