"""Updates

Revision ID: b00f8b36078a
Revises: 6ee60e85e953
Create Date: 2025-01-08 19:06:42.751828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00f8b36078a'
down_revision: Union[str, None] = '6ee60e85e953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fundsRaised', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'fundsRaised')
    # ### end Alembic commands ###
