"""Updated models to include other_details field

Revision ID: c4229174fb12
Revises: 
Create Date: 2025-01-06 18:56:00.584128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4229174fb12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('other_details', sa.Text(), nullable=True))
    op.add_column('founders', sa.Column('other_details', sa.Text(), nullable=True))
    op.add_column('investments', sa.Column('other_details', sa.Text(), nullable=True))
    op.add_column('investors', sa.Column('other_details', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('other_details', sa.Text(), nullable=True))
    op.add_column('updates', sa.Column('other_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'other_details')
    op.drop_column('projects', 'other_details')
    op.drop_column('investors', 'other_details')
    op.drop_column('investments', 'other_details')
    op.drop_column('founders', 'other_details')
    op.drop_column('admins', 'other_details')
    # ### end Alembic commands ###
