"""Added some fields to the tables

Revision ID: db8c99cf0a40
Revises: c4229174fb12
Create Date: 2025-01-06 20:05:42.120043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8c99cf0a40'
down_revision: Union[str, None] = 'c4229174fb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('founders', sa.Column('companyName', sa.String(), nullable=True))
    op.add_column('founders', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('founders', sa.Column('role', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('investmentFocus', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('investmentBudget', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('investmetSector', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('investmentExperience', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('linkedInProfile', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investors', 'role')
    op.drop_column('investors', 'linkedInProfile')
    op.drop_column('investors', 'investmentExperience')
    op.drop_column('investors', 'investmetSector')
    op.drop_column('investors', 'investmentBudget')
    op.drop_column('investors', 'investmentFocus')
    op.drop_column('founders', 'role')
    op.drop_column('founders', 'industry')
    op.drop_column('founders', 'companyName')
    # ### end Alembic commands ###
