"""Upadtes

Revision ID: ef7c8d500b38
Revises: b00f8b36078a
Create Date: 2025-01-08 23:07:07.039042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7c8d500b38'
down_revision: Union[str, None] = 'b00f8b36078a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'title')
    # ### end Alembic commands ###
